<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_58284ebe703e9',
        'title' => 'Servicios',
        'fields' => array (
            array (
                'key' => 'field_583feb9cb4d06',
                'label' => 'Detalles del Servicio',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58284ec217aa9',
                'label' => 'Descripción',
                'name' => 'mgdbq2josn_descripcion',
                'type' => 'textarea',
                'instructions' => 'Describe qué resultados devuelve este servicio.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'br',
            ),
            array (
                'key' => 'field_58286c3829fbe',
                'label' => 'Conector',
                'name' => 'mgdbq2josn_connector',
                'type' => 'relationship',
                'instructions' => 'Seleccione el conector para ejecutar la consulta SQL.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'mg_connector',
                ),
                'taxonomy' => array (
                ),
                'filters' => '',
                'elements' => '',
                'min' => 1,
                'max' => 1,
                'return_format' => 'id',
            ),
            array (
                'key' => 'field_58286b6517aaa',
                'label' => 'Consulta SQL',
                'name' => 'mgdbq2josn_query',
                'type' => 'textarea',
                'instructions' => 'Inserte la consulta SQL. Los valores de los parámetros deberán ser indicados entre llaves dobles, ej.: where codigo_postal = {{codigo_postal}}',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array (
                'key' => 'field_58286bd317aab',
                'label' => 'Nombre del servicio',
                'name' => 'mgdbq2josn_servicename',
                'type' => 'text',
                'instructions' => 'Indique el nombre que recibe el servicio en la REST API ej.: "consulta-padron-rivas"
(sin espacios o signos)',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'nombre-de-servicio',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_583febc6b4d07',
                'label' => 'Permisos de uso',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_583febffb4d08',
                'label' => 'Usuarios',
                'name' => 'mgdbq2josn_service_users',
                'type' => 'user',
                'instructions' => 'Indique los usuarios que pueden acceder al servicio.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'role' => '',
                'allow_null' => 0,
                'multiple' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mg_service',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            14 => 'send-trackbacks',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;